version: "3.7"
services:
  encryptor_fe_aes:
    build:
      context: .
    platform: linux/amd64
    volumes:
      - ..:/app
    working_dir: /app/
    command: >
      bash -c "conda run --no-capture-output -n sage-env uvicorn api_zip:app --host 0.0.0.0 --port 8000 &
               conda run --no-capture-output -n sage-env uvicorn api_aes:app --host 0.0.0.0 --port 8001"
